//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.PowerToys.Run.Plugin.GitHubRepo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.PowerToys.Run.Plugin.GitHubRepo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub authentication token.
        /// </summary>
        public static string plugin_auth_token {
            get {
                return ResourceManager.GetString("plugin_auth_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default user for searching.
        /// </summary>
        public static string plugin_default_user {
            get {
                return ResourceManager.GetString("plugin_default_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default user is not set.
        /// </summary>
        public static string plugin_default_user_not_set {
            get {
                return ResourceManager.GetString("plugin_default_user_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change in settings.
        /// </summary>
        public static string plugin_default_user_not_set_description {
            get {
                return ResourceManager.GetString("plugin_default_user_not_set_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search a GitHub repository.
        /// </summary>
        public static string plugin_description {
            get {
                return ResourceManager.GetString("plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open github.com.
        /// </summary>
        public static string plugin_empty_description {
            get {
                return ResourceManager.GetString("plugin_empty_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In {0}.
        /// </summary>
        public static string plugin_in_browser_name {
            get {
                return ResourceManager.GetString("plugin_in_browser_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Repository.
        /// </summary>
        public static string plugin_name {
            get {
                return ResourceManager.GetString("plugin_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories not found.
        /// </summary>
        public static string plugin_no_results {
            get {
                return ResourceManager.GetString("plugin_no_results", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open issues (Ctrl+I).
        /// </summary>
        public static string plugin_open_issues {
            get {
                return ResourceManager.GetString("plugin_open_issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open pull requests (Ctrl+P).
        /// </summary>
        public static string plugin_open_pull_requests {
            get {
                return ResourceManager.GetString("plugin_open_pull_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to open {0}..
        /// </summary>
        public static string plugin_search_failed {
            get {
                return ResourceManager.GetString("plugin_search_failed", resourceCulture);
            }
        }
    }
}
