//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Community.PowerToys.Run.Plugin.GitHubRepo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Community.PowerToys.Run.Plugin.GitHubRepo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy link (Ctrl+C).
        /// </summary>
        internal static string context_copy_link {
            get {
                return ResourceManager.GetString("context_copy_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open issues (Ctrl+I).
        /// </summary>
        internal static string context_open_issues {
            get {
                return ResourceManager.GetString("context_open_issues", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open pull requests (Ctrl+P).
        /// </summary>
        internal static string context_open_pull_requests {
            get {
                return ResourceManager.GetString("context_open_pull_requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default user is not set.
        /// </summary>
        internal static string default_user_not_set {
            get {
                return ResourceManager.GetString("default_user_not_set", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change in settings.
        /// </summary>
        internal static string default_user_not_set_description {
            get {
                return ResourceManager.GetString("default_user_not_set_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In {0}.
        /// </summary>
        internal static string in_browser_name {
            get {
                return ResourceManager.GetString("in_browser_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open github.com.
        /// </summary>
        internal static string open_github {
            get {
                return ResourceManager.GetString("open_github", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub authentication token.
        /// </summary>
        internal static string option_auth_token {
            get {
                return ResourceManager.GetString("option_auth_token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default user.
        /// </summary>
        internal static string option_default_user {
            get {
                return ResourceManager.GetString("option_default_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user used when type "/".
        /// </summary>
        internal static string option_default_user_desc {
            get {
                return ResourceManager.GetString("option_default_user_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of results.
        /// </summary>
        internal static string option_results_number {
            get {
                return ResourceManager.GetString("option_results_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose how many results to load each time.
        /// </summary>
        internal static string option_results_number_desc {
            get {
                return ResourceManager.GetString("option_results_number_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search self-hosted GitHub.
        /// </summary>
        internal static string option_self_host_link {
            get {
                return ResourceManager.GetString("option_self_host_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This replaces default url used.
        /// </summary>
        internal static string option_self_host_link_desc {
            get {
                return ResourceManager.GetString("option_self_host_link_desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url of API endpoint.
        /// </summary>
        internal static string option_url {
            get {
                return ResourceManager.GetString("option_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search a GitHub repository.
        /// </summary>
        internal static string plugin_description {
            get {
                return ResourceManager.GetString("plugin_description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GitHub Repository.
        /// </summary>
        internal static string plugin_name {
            get {
                return ResourceManager.GetString("plugin_name", resourceCulture);
            }
        }
    }
}
